/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalkRouteImport } from './routes/talk'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MedicinesRouteImport } from './routes/medicines'
import { Route as IndexRouteImport } from './routes/index'

const TalkRoute = TalkRouteImport.update({
  id: '/talk',
  path: '/talk',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesRoute = MedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/medicines': typeof MedicinesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/talk': typeof TalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/medicines': typeof MedicinesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/talk': typeof TalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/medicines': typeof MedicinesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/talk': typeof TalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/medicines' | '/reports' | '/settings' | '/talk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/medicines' | '/reports' | '/settings' | '/talk'
  id: '__root__' | '/' | '/medicines' | '/reports' | '/settings' | '/talk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MedicinesRoute: typeof MedicinesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TalkRoute: typeof TalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talk': {
      id: '/talk'
      path: '/talk'
      fullPath: '/talk'
      preLoaderRoute: typeof TalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines': {
      id: '/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof MedicinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MedicinesRoute: MedicinesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TalkRoute: TalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
